In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("C:/Users/HP/Downloads/qatarretail.xlsx")

In [5]:
df.head(10)

,Order ID,Order Date,Customer ID,City,Salesperson,Product,Category,Quantity,Unit Price,Discount,Sales Channel,Payment Method,Customer Type,Revenue,Cost,Profit
0,ORD-100000,2025-05-03,CUST-1056,Lusail,Mariam,Monitor,Electronics,7,978.52,0.05,Retail,Card,Enterprise,6507.16,4462.46,2044.70
1,ORD-100001,2025-03-19,CUST-1468,Doha,Fatima,Phone,Electronics,5,2691.46,0.05,online,Bank Transfer,SME,12784.44,9210.00,3574.44
2,ORD-100002,2025-06-18,CUST-1378,Al Rayyan,Yousef,Office Chair,Furniture,2,1202.06,0.08,Retail,Cash,Individual,2211.79,1560.06,651.73
3,ORD-100003,2026-06-28,CUST-1298,Doha,Khalid,Projector,Office Equipment,4,2070.42,0.10,Retail,Card,Enterprise,7453.51,5770.71,1682.80
4,ORD-100004,2025-02-16,CUST-1281,doha,Sara,Projector,Office Equipment,6,2056.97,0.15,Corporate,Card,Enterprise,10490.55,8312.00,2178.55
5,ORD-100005,2025-05-18,CUST-1460,doha,Fatima,Office Chair,Furniture,3,1287.16,0.08,online,Credit,SME,3552.56,2317.15,1235.41
6,ORD-100006,2026-05-05,CUST-1004,doha,Yousef,Router,Networking,3,423.76,0.08,Retail,Card,SME,1169.58,765.28,404.30
7,ORD-100007,2026-04-20,CUST-1147,Doha,Fatima,Tablet,Electronics,3,1754.00,0.05,Retail,Card,SME,4998.90,3719.05,1279.85
8,ORD-100008,2025-02-25,CUST-1335,doha,Omar,Router,Networking,5,422.73,0.10,Retail,Card,SME,1902.28,1271.98,630.30
9,ORD-100009,2025-05-11,CUST-1493,Doha,Yousef,Office Chair,Furniture,8,1186.22,0.05,Online,Credit,SME,9015.27,5873.29,3141.98

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4012 entries, 0 to 4011
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        4012 non-null   object
 1   Order Date      4012 non-null   datetime64[ns]
 2   Customer ID     4012 non-null   object
 3   City            3976 non-null   object
 4   Salesperson     3992 non-null   object
 5   Product         3994 non-null   object
 6   Category        4012 non-null   object
 7   Quantity        4012 non-null   int64
 8   Unit Price      4012 non-null   float64
 9   Discount        3997 non-null   float64
 10  Sales Channel   4012 non-null   object
 11  Payment Method  3987 non-null   object
 12  Customer Type   4012 non-null   object
 13  Revenue         4012 non-null   float64
 14  Cost            4012 non-null   float64
 15  Profit          4012 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 501.6+ KB

In [11]:
#find out the nulls in each column and their reasons
nullvalues = pd.DataFrame ({
    'null values' : df.isnull().sum(),
    'null %' : (df.isna().sum() / len(df) * 100).round(2)
})

nullvalues

                null values  null %
Order ID                  0    0.00
Order Date                0    0.00
Customer ID               0    0.00
City                     36    0.90
Salesperson              20    0.50
Product                  18    0.45
Category                  0    0.00
Quantity                  0    0.00
Unit Price                0    0.00
Discount                 15    0.37
Sales Channel             0    0.00
Payment Method           25    0.62
Customer Type             0    0.00
Revenue                   0    0.00
Cost                      0    0.00
Profit                    0    0.00

In [15]:
#null values in payment method section are treated as cash payments
df['Payment Method'] = df['Payment Method'].fillna('Cash')

#city,product,salesperson null values are filled as unknown
df['City'] = df['City'].fillna('Unknown')
df['Salesperson'] = df['Salesperson'].fillna('Unknown')
df['Product'] = df['Product'].fillna('Unknown')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4012 entries, 0 to 4011
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        4012 non-null   object
 1   Order Date      4012 non-null   datetime64[ns]
 2   Customer ID     4012 non-null   object
 3   City            4012 non-null   object
 4   Salesperson     4012 non-null   object
 5   Product         4012 non-null   object
 6   Category        4012 non-null   object
 7   Quantity        4012 non-null   int64
 8   Unit Price      4012 non-null   float64
 9   Discount        3997 non-null   float64
 10  Sales Channel   4012 non-null   object
 11  Payment Method  4012 non-null   object
 12  Customer Type   4012 non-null   object
 13  Revenue         4012 non-null   float64
 14  Cost            4012 non-null   float64
 15  Profit          4012 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 501.6+ KB

In [27]:
#discount null values are filled with 0, assuming no discount is given on those dates or products
df.loc[df['Discount'].isnull()][['Order Date', 'Product']]

     Order Date       Product
83   2025-01-23         Phone
425  2025-12-25         Phone
487  2026-03-25        Laptop
538  2026-03-25  Office Chair
572  2026-02-18         Phone
970  2025-12-23       Monitor
1231 2025-04-08        Laptop
1669 2026-01-20       Printer
1859 2026-02-22          Desk
2005 2025-12-07       Printer
3051 2026-01-26        Tablet
3095 2025-07-02       Printer
3172 2026-04-18        Router
3576 2025-05-03       Monitor
3650 2025-01-15  Office Chair

In [31]:
df['Discount'] = df['Discount'].fillna('0')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4012 entries, 0 to 4011
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        4012 non-null   object
 1   Order Date      4012 non-null   datetime64[ns]
 2   Customer ID     4012 non-null   object
 3   City            4012 non-null   object
 4   Salesperson     4012 non-null   object
 5   Product         4012 non-null   object
 6   Category        4012 non-null   object
 7   Quantity        4012 non-null   int64
 8   Unit Price      4012 non-null   float64
 9   Discount        4012 non-null   object
 10  Sales Channel   4012 non-null   object
 11  Payment Method  4012 non-null   object
 12  Customer Type   4012 non-null   object
 13  Revenue         4012 non-null   float64
 14  Cost            4012 non-null   float64
 15  Profit          4012 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(10)
memory usage: 501.6+ KB

In [45]:
df = df.sort_values('Order Date').reset_index(drop = True)

In [47]:
#learning demand patterns over given conditions
x = df[['City', 'Product', 'Category', 'Unit Price', 'Discount', 'Sales Channel', 'Customer Type']]
y = df['Quantity']

In [49]:
from xgboost import XGBRegressor

In [61]:
xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    random_state=42
)

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_cols = [
    'City',
    'Product',
    'Category',
    'Sales Channel',
    'Customer Type'
]

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='passthrough'
)

x_encoded = preprocessor.fit_transform(x)

x_encoded.shape

(4012, 35)

In [65]:
test_size = int(x_encoded.shape[0] * 0.2)

x1_train = x_encoded[:-test_size]
x1_test = x_encoded[-test_size:]

y1_train = y.iloc[:-test_size]
y1_test = y.iloc[-test_size:]

In [67]:
xgb_model.fit(x1_train, y1_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [69]:
y_pred = xgb_model.predict(x1_test)

In [73]:
predicted = pd.DataFrame({
    'actual values' : y1_test.values,
    'xgb pred' : y_pred
    })
predicted

     actual values  xgb pred
0                5  4.065098
1                5  4.750121
2                7  4.279761
3                7  4.784261
4                7  4.296987
..             ...       ...
797              4  4.695807
798              4  4.747794
799              2  4.588876
800              4  5.179825
801              8  3.761662

[802 rows x 2 columns]

In [75]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [77]:
mae = mean_absolute_error(y1_test, y_pred)
mse = mean_squared_error(y1_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y1_test, y_pred)

In [79]:
mae

2.071816425073771

In [81]:
mse

6.06684885080875

In [83]:
rmse

2.46309740993099

In [85]:
r2

-0.15725340460988657

In [89]:
y1_train.describe()

count    3210.000000
mean        4.542056
std         2.639963
min         1.000000
25%         2.000000
50%         5.000000
75%         6.000000
max        40.000000
Name: Quantity, dtype: float64

In [93]:
y1_test.describe()

count    802.000000
mean       4.571072
std        2.291070
min        0.000000
25%        3.000000
50%        5.000000
75%        7.000000
max        8.000000
Name: Quantity, dtype: float64

In [95]:
y.value_counts().sort_index()

Quantity
0       1
1     502
2     497
3     500
4     484
5     523
6     503
7     480
8     517
25      1
40      4
Name: count, dtype: int64

In [97]:
print("Actual:   ", y1_test.iloc[:20].values)
print("Predicted:", np.round(y_pred[:20], 2))

Actual:    [5 5 7 7 7 7 7 4 6 4 4 8 1 2 7 8 3 8 6 4]
Predicted: [4.07 4.75 4.28 4.78 4.3  3.7  4.67 5.07 4.66 3.73 4.46 4.86 4.53 4.64
 4.5  4.61 5.06 5.16 4.15 4.03]

In [99]:
print("Mean actual:", y1_test.mean())
print("Mean predicted:", y_pred.mean())

Mean actual: 4.571072319201995
Mean predicted: 4.51895

In [103]:
df.groupby('Product')['Quantity'].mean().sort_values()
df.groupby('Category')['Quantity'].mean().sort_values()
df.groupby('Sales Channel')['Quantity'].mean().sort_values()

Sales Channel
online       4.485075
Retail       4.485627
Online       4.558862
Corporate    4.727500
Name: Quantity, dtype: float64

In [105]:
df.groupby('Product')['Quantity'].mean().sort_values()

Product
Monitor         4.270833
Printer         4.285714
Router          4.384858
Laptop          4.439252
Office Chair    4.562857
Keyboard        4.564669
Mouse           4.568389
Tablet          4.621875
Headset         4.624294
Phone           4.718232
Unknown         4.722222
Desk            4.740741
Projector       4.748538
Name: Quantity, dtype: float64

In [107]:
df.groupby('Category')['Quantity'].mean().sort_values()

Category
Networking          4.393082
Electronics         4.512286
Office Equipment    4.518741
Accessories         4.586653
Furniture           4.661765
Name: Quantity, dtype: float64

In [113]:
xgb_model.feature_importances_

array([0.1060557 , 0.03181296, 0.0377123 , 0.05196712, 0.0906769 ,
       0.02717343, 0.01091554, 0.02855253, 0.0221567 , 0.02044135,
       0.05719666, 0.01021136, 0.02796954, 0.02653043, 0.02248498,
       0.01095802, 0.02180544, 0.04818413, 0.00688315, 0.02007774,
       0.00628006, 0.        , 0.02415765, 0.02091823, 0.00414891,
       0.03590071, 0.02366646, 0.01928031, 0.0205116 , 0.01994939,
       0.05013357, 0.02105849, 0.02646951, 0.02334174, 0.02441739],
      dtype=float32)