In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("C:/Users/HP/Downloads/qatarretail.xlsx")

In [5]:
df.head(10)

,Order ID,Order Date,Customer ID,City,Salesperson,Product,Category,Quantity,Unit Price,Discount,Sales Channel,Payment Method,Customer Type,Revenue,Cost,Profit
0,ORD-100000,2025-05-03,CUST-1056,Lusail,Mariam,Monitor,Electronics,7,978.52,0.05,Retail,Card,Enterprise,6507.16,4462.46,2044.70
1,ORD-100001,2025-03-19,CUST-1468,Doha,Fatima,Phone,Electronics,5,2691.46,0.05,online,Bank Transfer,SME,12784.44,9210.00,3574.44
2,ORD-100002,2025-06-18,CUST-1378,Al Rayyan,Yousef,Office Chair,Furniture,2,1202.06,0.08,Retail,Cash,Individual,2211.79,1560.06,651.73
3,ORD-100003,2026-06-28,CUST-1298,Doha,Khalid,Projector,Office Equipment,4,2070.42,0.10,Retail,Card,Enterprise,7453.51,5770.71,1682.80
4,ORD-100004,2025-02-16,CUST-1281,doha,Sara,Projector,Office Equipment,6,2056.97,0.15,Corporate,Card,Enterprise,10490.55,8312.00,2178.55
5,ORD-100005,2025-05-18,CUST-1460,doha,Fatima,Office Chair,Furniture,3,1287.16,0.08,online,Credit,SME,3552.56,2317.15,1235.41
6,ORD-100006,2026-05-05,CUST-1004,doha,Yousef,Router,Networking,3,423.76,0.08,Retail,Card,SME,1169.58,765.28,404.30
7,ORD-100007,2026-04-20,CUST-1147,Doha,Fatima,Tablet,Electronics,3,1754.00,0.05,Retail,Card,SME,4998.90,3719.05,1279.85
8,ORD-100008,2025-02-25,CUST-1335,doha,Omar,Router,Networking,5,422.73,0.10,Retail,Card,SME,1902.28,1271.98,630.30
9,ORD-100009,2025-05-11,CUST-1493,Doha,Yousef,Office Chair,Furniture,8,1186.22,0.05,Online,Credit,SME,9015.27,5873.29,3141.98

In [6]:
df[['Order Date', 'Revenue', 'Profit', 'Quantity', 'Discount']]

     Order Date   Revenue   Profit  Quantity  Discount
0    2025-05-03   6507.16  2044.70         7      0.05
1    2025-03-19  12784.44  3574.44         5      0.05
2    2025-06-18   2211.79   651.73         2      0.08
3    2026-06-28   7453.51  1682.80         4      0.10
4    2025-02-16  10490.55  2178.55         6      0.15
...         ...       ...      ...       ...       ...
4007 2026-07-01   1301.81   398.08         6      0.20
4008 2025-02-24    398.93   164.63         2      0.08
4009 2026-08-30   6436.47  2264.82         3      0.05
4010 2026-02-07   6870.96  1675.66         5      0.20
4011 2025-03-18   8080.74  2548.99         3      0.00

[4012 rows x 5 columns]

In [7]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [12]:
df['Order Date']

0      2025-05-03
1      2025-03-19
2      2025-06-18
3      2026-06-28
4      2025-02-16
          ...
4007   2026-07-01
4008   2025-02-24
4009   2026-08-30
4010   2026-02-07
4011   2025-03-18
Name: Order Date, Length: 4012, dtype: datetime64[ns]

In [14]:
monthly = (
    df.groupby(df['Order Date'].dt.to_period('M')).agg(
    Revenue = ('Revenue', 'sum'),
    Quantity = ('Quantity', 'sum'),
    Profit = ('Profit', 'sum'),
    Discount = ('Discount', 'mean')
)
.reset_index() 
)

In [16]:
monthly

   Order Date     Revenue  Quantity     Profit  Discount
0     2025-01  1090547.79      1003  319787.87  0.067945
1     2025-02  1042239.69       808  284389.14  0.066833
2     2025-03  1206928.02       975  349501.68  0.056351
3     2025-04  1302057.83      1042  373783.72  0.062143
4     2025-05  1162917.87       903  325752.13  0.063505
5     2025-06  1216757.91       925  387785.92  0.064974
6     2025-07  1125021.11       924  319930.30  0.061950
7     2025-08   947515.09       867  273029.07  0.070201
8     2025-09  1080073.26       932  310119.20  0.062370
9     2025-10   967962.03       845  291676.95  0.064635
10    2025-11  1120684.57       873  321495.35  0.060942
11    2025-12  1112096.64       884  365989.18  0.062359
12    2026-01  1144063.99       938  322214.72  0.058899
13    2026-02   938967.32       756  271934.53  0.060123
14    2026-03  1335062.47      1007  436849.91  0.058048
15    2026-04  1230374.25       972  351882.73  0.057156
16    2026-05  1143305.34       880  333854.95  0.060718
17    2026-06  1051267.87       855  303967.89  0.063027
18    2026-07  1023209.63       965  289789.80  0.065714
19    2026-08  1088113.64       892  330818.89  0.059697

In [18]:
monthly['Last Month'] = monthly['Revenue'].shift(1)
monthly['2 months ago'] = monthly['Revenue'].shift(2)
monthly['3 months ago'] = monthly['Revenue'].shift(3)

In [ ]:
monthly.head()

In [23]:
monthly['roll_avg'] = (
    monthly['Revenue']
    .shift(1)
    .rolling(3)
    .mean()
)

In [25]:
monthly.head()

,Order Date,Revenue,Quantity,Profit,Discount,Last Month,2 months ago,3 months ago,roll_avg
0,2025-01,1090547.79,1003,319787.87,0.067945,NaN,NaN,NaN,NaN
1,2025-02,1042239.69,808,284389.14,0.066833,1090547.79,NaN,NaN,NaN
2,2025-03,1206928.02,975,349501.68,0.056351,1042239.69,1090547.79,NaN,NaN
3,2025-04,1302057.83,1042,373783.72,0.062143,1206928.02,1042239.69,1090547.79,1.113238e+06
4,2025-05,1162917.87,903,325752.13,0.063505,1302057.83,1206928.02,1042239.69,1.183742e+06

In [27]:
monthly = monthly.dropna()

In [29]:
monthly.head()

,Order Date,Revenue,Quantity,Profit,Discount,Last Month,2 months ago,3 months ago,roll_avg
3,2025-04,1302057.83,1042,373783.72,0.062143,1206928.02,1042239.69,1090547.79,1.113238e+06
4,2025-05,1162917.87,903,325752.13,0.063505,1302057.83,1206928.02,1042239.69,1.183742e+06
5,2025-06,1216757.91,925,387785.92,0.064974,1162917.87,1302057.83,1206928.02,1.223968e+06
6,2025-07,1125021.11,924,319930.30,0.061950,1216757.91,1162917.87,1302057.83,1.227245e+06
7,2025-08,947515.09,867,273029.07,0.070201,1125021.11,1216757.91,1162917.87,1.168232e+06

In [31]:
x = monthly[['Last Month', '2 months ago', '3 months ago', 'roll_avg']]
y = monthly['Revenue']

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_scor np

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [38]:
X_train = x.iloc[:-4]
X_test = x.iloc[-4:]

y_train = y.iloc[:-4]
y_test = y.iloc[-4:]

In [40]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [42]:
y_pred = model.predict(X_test)

print(y_pred)

[1204636.90193254 1058619.04448658 1195965.89691856 1080708.2277432 ]

In [44]:
comparison = pd.DataFrame({
    'Actual Revenue': y_test.values,
    'Predicted Revenue': y_pred
})

comparison

   Actual Revenue  Predicted Revenue
0      1143305.34       1.204637e+06
1      1051267.87       1.058619e+06
2      1023209.63       1.195966e+06
3      1088113.64       1.080708e+06

In [46]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 62211.103898620844
RMSE: 91808.45296832312
R²: -3.175588450668628

In [226]:
from xgboost import XGBRegressor

In [50]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB 682.7 kB/s eta 0:01:12
   ---------------------------------------- 0.0/48.9 MB 660.6 kB/s eta 0:01:15
   ---------------------------------------- 0.1/48.9 MB 469.7 kB/s eta 0:01:45
   ---------------------------------------- 0.1/48.9 MB 585.1 kB/s eta 0:01:24
   ---------------------------------------- 0.2/48.9 MB 655.4 kB/s eta 0:01:15
   ---------------------------------------- 0.2/48.9 MB 811.5 kB/s eta 0:01:01
   ---------------------------------------- 0.3/48.9 MB 865.8 kB/s eta 0:00:57
   ---------------------------------------- 0.5/48.9 MB 1.3 MB/s eta 0:00:39
   ---------------------------------------- 0.5/48.9 MB 1.1 MB/s eta 0:00:43
    --------------------------------------- 0.9/48.9 MB 1.8 MB/s eta 0:00:27
    --------------------------------------- 1.0/48.9 MB 1.9 MB/s eta 0:00:26
   - -------------------------------------- 1.5/48.9 MB 2.6 MB/s eta 0:00:19
   - -------------------------------------- 2.1/48.9 MB 3.4 MB/s eta 0:00:14
   -- ------------------------------------- 2.6/48.9 MB 3.9 MB/s eta 0:00:13
   --- ------------------------------------ 3.9/48.9 MB 5.4 MB/s eta 0:00:09
   --- ------------------------------------ 4.2/48.9 MB 5.5 MB/s eta 0:00:09
   ----- ---------------------------------- 6.5/48.9 MB 8.0 MB/s eta 0:00:06
   ------ --------------------------------- 8.3/48.9 MB 9.9 MB/s eta 0:00:05
   ------- -------------------------------- 8.7/48.9 MB 9.6 MB/s eta 0:00:05
   --------- ------------------------------ 11.2/48.9 MB 21.8 MB/s eta 0:00:02
   ---------- ----------------------------- 13.3/48.9 MB 34.4 MB/s eta 0:00:02
   ----------- ---------------------------- 13.9/48.9 MB 31.2 MB/s eta 0:00:02
   ------------- -------------------------- 15.9/48.9 MB 34.4 MB/s eta 0:00:01
   ------------- -------------------------- 15.9/48.9 MB 34.4 MB/s eta 0:00:01
   ------------- -------------------------- 15.9/48.9 MB 34.4 MB/s eta 0:00:01
   ------------- -------------------------- 15.9/48.9 MB 34.4 MB/s eta 0:00:01
   ------------- -------------------------- 15.9/48.9 MB 34.4 MB/s eta 0:00:01
   ------------- -------------------------- 16.8/48.9 MB 19.8 MB/s eta 0:00:02
   ----------------- ---------------------- 21.1/48.9 MB 24.2 MB/s eta 0:00:02
   ----------------- ---------------------- 21.2/48.9 MB 21.9 MB/s eta 0:00:02
   ------------------ --------------------- 22.4/48.9 MB 20.5 MB/s eta 0:00:02
   -------------------- ------------------- 25.4/48.9 MB 23.4 MB/s eta 0:00:02
   ----------------------- ---------------- 28.4/48.9 MB 46.7 MB/s eta 0:00:01
   ------------------------ --------------- 30.2/48.9 MB 40.9 MB/s eta 0:00:01
   ------------------------- -------------- 31.2/48.9 MB 34.4 MB/s eta 0:00:01
   --------------------------- ------------ 33.2/48.9 MB 46.7 MB/s eta 0:00:01
   ---------------------------- ----------- 34.9/48.9 MB 43.7 MB/s eta 0:00:01
   ----------------------------- ---------- 36.1/48.9 MB 40.9 MB/s eta 0:00:01
   ----------------------------- ---------- 36.1/48.9 MB 40.9 MB/s eta 0:00:01
   ----------------------------- ---------- 36.1/48.9 MB 40.9 MB/s eta 0:00:01
   ----------------------------- ---------- 36.1/48.9 MB 40.9 MB/s eta 0:00:01
   ----------------------------- ---------- 36.6/48.9 MB 22.6 MB/s eta 0:00:01
   ------------------------------- -------- 38.2/48.9 MB 21.1 MB/s eta 0:00:01
   -------------------------------- ------- 40.3/48.9 MB 21.8 MB/s eta 0:00:01
   ---------------------------------- ----- 42.2/48.9 MB 22.5 MB/s eta 0:00:01
   ------------------------------------ --- 44.1/48.9 MB 21.8 MB/s eta 0:00:01
   -------------------------------------- - 46.9/48.9 MB 40.9 MB/s eta 0:00:01
   ---------------------------------------  48.9/48.9 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------  48.9/48.9 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------  48.9/48.9 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------  48.9/48.9 MB 46.7 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 25.1 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1

In [52]:
from xgboost import XGBRegressor

In [54]:
xgb_model = XGBRegressor(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    random_state=42
)

In [56]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [58]:
xgb_pred = xgb_model.predict(X_test)

In [60]:
xgb_mae = mean_absolute_error(y_test, xgb_pred)
xgb_mse = mean_squared_error(y_test, xgb_pred)
xgb_rmse = np.sqrt(xgb_mse)
xgb_r2 = r2_score(y_test, xgb_pred)

print("XGBoost MAE:", xgb_mae)
print("XGBoost RMSE:", xgb_rmse)
print("XGBoost R²:", xgb_r2)

XGBoost MAE: 72018.15312499998
XGBoost RMSE: 81768.2871240034
XGBoost R²: -2.3122426849154154

In [62]:
xgb_comparison = pd.DataFrame({
    'Actual Revenue': y_test.values,
    'XGBoost Prediction': xgb_pred
})

xgb_comparison

   Actual Revenue  XGBoost Prediction
0      1143305.34        1.162560e+06
1      1051267.87        9.507239e+05
2      1023209.63        9.715244e+05
3      1088113.64        9.715244e+05

In [146]:
df = df.sort_values('Order Date').reset_index(drop=True)

In [148]:
df.head()

,Order ID,Order Date,Customer ID,City,Salesperson,Product,Category,Quantity,Unit Price,Discount,Sales Channel,Payment Method,Customer Type,Revenue,Cost,Profit
0,ORD-102372,2025-01-01,CUST-1250,doha,Khalid,Monitor,Electronics,6,885.27,0.02,Online,Cash,Individual,5205.39,3791.24,1414.15
1,ORD-102941,2025-01-01,CUST-1179,Doha,Omar,Laptop,Electronics,2,3387.07,0.15,online,Card,Individual,5758.02,4734.63,1023.39
2,ORD-103588,2025-01-01,CUST-1200,Lusail,Mariam,Printer,Office Equipment,3,742.52,0.10,online,Card,Individual,2004.80,1516.01,488.79
3,ORD-100603,2025-01-01,CUST-1516,doha,Khalid,Tablet,Electronics,2,1800.48,0.08,Retail,Cash,Individual,3312.88,2442.35,870.53
4,ORD-103876,2025-01-01,CUST-1236,Al-Rayyan,Fatima,Office Chair,Furniture,1,1282.94,0.00,online,Card,SME,1282.94,753.08,529.86

In [150]:
x1 = df[['Cost', 'Discount']]
y1 = df['Revenue']

In [ ]:
x1_train, x1_test, y1_train, y2_test = train_test_split (x1, y1, test_size = 0.4)

In [66]:
x1_train = x1.iloc[:-4]
x1_test = x1.iloc[-4:]

y1_train = y1.iloc[:-4]
y1_test = y1.iloc[-4:]

In [82]:
trainset = df[['Cost', 'Discount']]

In [86]:
trainset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4012 entries, 0 to 4011
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Cost      4012 non-null   float64
 1   Discount  3997 non-null   float64
dtypes: float64(2)
memory usage: 62.8 KB

In [96]:
trainset['Discount'].isna().sum()

15

In [104]:
df.loc[df['Discount'].isna()][['Order Date', 'Category']]

     Order Date          Category
83   2025-01-23       Electronics
425  2025-12-25       Electronics
487  2026-03-25       Electronics
538  2026-03-25         Furniture
572  2026-02-18       Electronics
970  2025-12-23       Electronics
1231 2025-04-08       Electronics
1669 2026-01-20  Office Equipment
1859 2026-02-22         Furniture
2005 2025-12-07  Office Equipment
3051 2026-01-26       Electronics
3095 2025-07-02  Office Equipment
3172 2026-04-18        Networking
3576 2025-05-03       Electronics
3650 2025-01-15         Furniture

In [152]:
df['Discount'] = df['Discount'].fillna(0)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4012 entries, 0 to 4011
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        4012 non-null   object
 1   Order Date      4012 non-null   datetime64[ns]
 2   Customer ID     4012 non-null   object
 3   City            3976 non-null   object
 4   Salesperson     3992 non-null   object
 5   Product         3994 non-null   object
 6   Category        4012 non-null   object
 7   Quantity        4012 non-null   int64
 8   Unit Price      4012 non-null   float64
 9   Discount        4012 non-null   float64
 10  Sales Channel   4012 non-null   object
 11  Payment Method  3987 non-null   object
 12  Customer Type   4012 non-null   object
 13  Revenue         4012 non-null   float64
 14  Cost            4012 non-null   float64
 15  Profit          4012 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 501.6+ KB

In [156]:
x1 = df[['Cost', 'Discount']]
y1 = df['Revenue']

In [158]:
test_size = int(len(x1) * 0.2)

x1_train = x1.iloc[:-test_size]
x1_test = x1.iloc[-test_size:]

y1_train = y1.iloc[:-test_size]
y1_test = y1.iloc[-test_size:]

In [160]:
model = LinearRegression()

In [162]:
model.fit(x1_train, y1_train)

LinearRegression()

In [164]:
y_pred = model.predict(x1_test)

In [166]:
predicted = pd.DataFrame({
    'actual values' : y1_test.values,
    'pred values' : y_pred })
predicted

     actual values   pred values
0          4403.53   4446.028509
1         12886.21  11905.677360
2          1930.89   1825.257803
3         12090.39  11822.817677
4         22583.12  22848.510563
..             ...           ...
797        6232.12   5702.131837
798        6996.33   6030.426672
799         801.65    865.531132
800       11642.36  12627.801179
801         794.14    772.847192

[802 rows x 2 columns]

In [182]:
mae = mean_absolute_error(y1_test, y_pred)
mse = mean_squared_error(y1_test, y_pred)
rmse = np.sqrt(mse)

In [184]:
mae

445.2005961021729

In [186]:
mse

432421.0501858099

In [188]:
rmse

657.5872947265708

In [190]:
r2 = r2_score(y1_test, y_pred)

In [192]:
r2

0.9855791062558205

In [194]:
df[['Revenue', 'Cost', 'Discount']].corr()

           Revenue      Cost  Discount
Revenue   1.000000  0.932794 -0.036000
Cost      0.932794  1.000000  0.024053
Discount -0.036000  0.024053  1.000000

In [196]:
model.coef_

array([ 1.33300647e+00, -7.07921973e+03])

In [198]:
from xgboost import XGBRegressor

In [216]:
xgb_model = XGBRegressor(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    random_state=42
)

In [220]:
xgb_pred = xgb_model.predict(x1_test)

In [218]:
xgb_model.fit(x1_train, y1_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [222]:
print(len(y1_test))
print(len(xgb_pred))

802
802

In [224]:
xgb_mae = mean_absolute_error(y1_test, xgb_pred)
xgb_mse = mean_squared_error(y1_test, xgb_pred)
xgb_rmse = np.sqrt(xgb_mse)
xgb_r2 = r2_score(y1_test, xgb_pred)

print("XGBoost MAE:", xgb_mae)
print("XGBoost RMSE:", xgb_rmse)
print("XGBoost R²:", xgb_r2)

XGBoost MAE: 389.5823398702341
XGBoost RMSE: 742.2955633699008
XGBoost R²: 0.9816245036289212